language: node_js
sudo: false
node_js:
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libcairo2-dev
      - libjpeg8-dev
      - libpng12-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
before_script:
  - npm install -g tslint typescript tsd gulp
  - npm install
  - tsd install
script:
  - npm test -- --travis
